### ISSUE TITLE
代码处理问题

### ISSUE THREAD

**Issue by zhanghaozhe23** [hailanyi/CPD#3]
你好，祝贺你的工作！
我打算复现你的文章，我主要使用的是kitti数据集，但是我在kitti数据集的处理过程中貌似貌似遇到了一点问题：
1. 你的文件里似乎没有pcdet文件夹，我执行setup.py的时候会报错，我从你的CasA代码中将pcdet文件夹引入解决了问题
2. 在kitti数据集的处理命令中，voxel_rcnn_cproto_center_kitti.yaml貌似是模型文件而不是数据处理文件，但是当我替换成kitti2waymo_dataset.yaml文件，处理依然会报错。load() missing 1 required positional argument: 'Loader'
3. 你的kitti2waymo_dataset.py文件我不清楚和原来的kitti_dataset.py有什么区别，你的kitti2waymo_dataset.py第458行是不是应该改成Kitti2WaymoDataset
4. 你的文章中有针对前后时段帧的Motion Artifact Removal (MAR)操作，我不太清楚针对kitti数据集这种没有前后帧的数据集该如何操作

**Comment by hailanyi** [comment]
info 生成应该是有些bug的，我没在KITTI上用这个代码生成过info，我直接用的原版的kitti_dataset生成的info。另外我没在kitti上训练过model，只是拿waymo的model到kitti测试过。

一. 为了避免冲突，这个repo我把pcdet都换成cpd了，你直接换成pcdet加载不了cpd里的代码
二和三. 把503行改成 ```dataset_cfg = EasyDict(yaml.safe_load(open(sys.argv[2])))``` 把458改成 Kitti2WaymoDataset
四. 我没对kitti做训练，所以不需要做这一步
